deployment template: fix extraSidecars indentation (#770)
### Proposed changes

In the deployment template, the `extraSidecars` object is indented too
far, resulting in malformed YAML.

```yaml
# test-values.yaml
extraSidecars:
  - name: busy-beaver
    image: busybox
    command: ["sh", "-c"]
    args: ["sleep 999999"]
```

```sh
cd pulumi-kubernetes-operator/deploy/helm/pulumi-operator
helm template . -f test-values.yaml

Error: YAML parse error on pulumi-kubernetes-operator/templates/deployment.yaml: error converting YAML to JSON: yaml: line 34: did not find expected key
```

This change reduces the indentation to match the `manager` entry in the
`containers` list.

### Notes

* Ideally this can be included in the 0.8.x release train as 2.x is
still unreleased
* As far as I can tell, this has been an issue since the file was
introduced in #379
* Aside, the PR template has a reference to CONTRIBUTING.md, but that
file doesn't seem to exist in the repo